### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by sjomae** [agraef/xwiimote-lua#3]
xwiimote-lua]$ make
cc -shared -fPIC -o xwiilua.so xwiilua.c -lxwiimote -ludev  -llua -lm
xwiilua.c: In function ‘l_xwii_poll’:
xwiilua.c:302:14: error: ‘XWII_EVENT_CLASSIC_CONTROLLER_KEY’ undeclared (first use in this function); did you mean ‘XWII_EVENT_PRO_CONTROLLER_KEY’?
  302 |         case XWII_EVENT_CLASSIC_CONTROLLER_KEY:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XWII_EVENT_PRO_CONTROLLER_KEY
xwiilua.c:302:14: note: each undeclared identifier is reported only once for each function it appears in
xwiilua.c:304:14: error: ‘XWII_EVENT_NUNCHUK_KEY’ undeclared (first use in this function); did you mean ‘XWII_EVENT_KEY’?
  304 |         case XWII_EVENT_NUNCHUK_KEY:
      |              ^~~~~~~~~~~~~~~~~~~~~~
      |              XWII_EVENT_KEY
xwiilua.c:305:14: error: ‘XWII_EVENT_DRUMS_KEY’ undeclared (first use in this function); did you mean ‘XWII_EVENT_KEY’?
  305 |         case XWII_EVENT_DRUMS_KEY:
      |              ^~~~~~~~~~~~~~~~~~~~
      |              XWII_EVENT_KEY
xwiilua.c:306:14: error: ‘XWII_EVENT_GUITAR_KEY’ undeclared (first use in this function); did you mean ‘XWII_EVENT_KEY’?
  306 |         case XWII_EVENT_GUITAR_KEY:
      |              ^~~~~~~~~~~~~~~~~~~~~
      |              XWII_EVENT_KEY
xwiilua.c:332:14: error: ‘XWII_EVENT_GONE’ undeclared (first use in this function); did you mean ‘XWII_EVENT_NUM’?
  332 |         case XWII_EVENT_GONE:
      |              ^~~~~~~~~~~~~~~
      |              XWII_EVENT_NUM
xwiilua.c:357:14: error: ‘XWII_EVENT_CLASSIC_CONTROLLER_MOVE’ undeclared (first use in this function); did
you mean ‘XWII_EVENT_PRO_CONTROLLER_MOVE’?
  357 |         case XWII_EVENT_CLASSIC_CONTROLLER_MOVE:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XWII_EVENT_PRO_CONTROLLER_MOVE
xwiilua.c:368:14: error: ‘XWII_EVENT_NUNCHUK_MOVE’ undeclared (first use in this function)
  368 |         case XWII_EVENT_NUNCHUK_MOVE:
      |              ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:5: xwiilua.so] Error 1

**Comment by sjomae** [comment]
I've xwiimote.h, but it doesn't find it apparently @agraef 
usr/include/xwiimote.h

**Comment by sjomae** [comment]
Building xwiimote from source instead fixed it.

**Comment by agraef** [comment]
Hmm, maybe the Lua module requires a newer xwiimote version than what came installed on your system? Because the errors you reported don't indicate that the header file wasn't found, just that some of the manifest constants were missing.
